on:
  push:
    branches: master

name: R package

jobs:
  Rpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install enviorment
        run: |
          conda update --all
          conda install --channel "conda-forge" --channel "anaconda" --channel "r" tensorflow r-biocmanager gxx_linux-64 gcc_linux-64 keras jupyter jupytext numpy fontconfig pandas r-base r-rlang r-devtools r-pkgdown r-brio r-magick r-rgl r-rjava r-mnormt r-purrrogress r-xml libxml2 libmagic pandoc r-rjava opencv pkgconfig gfortran_linux-64
          echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile
          Rscript -e 'install.packages(c("devtools","remotes")); remotes::install_cran("pkgdown");'
          Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/kstawiski/OmicSelector/master/vignettes/setup.R")'

      - name: Install package
        run: R CMD INSTALL .

      - name: Check loading
        run: |
          Rscript -e 'library(OmicSelector); sessionInfo();'
