on:
  push:
    branches: master

name: R package

jobs:
  Rpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install enviorment
        run: |
          conda update --all
          conda install mamba -c conda-forge
          mamba install --channel "conda-forge" --channel "anaconda" --channel "r" r-base>4.0 keras jupyter jupytext numpy pandas libxml2 pandoc r-rjava r-magick libglu libx11-devel-cos6-x86_64 libgit2 xorg-libx11 mesa-libgl-cos6-x86_64 r-devtools r-rgl r-cairo r-gert opencv
          echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile
          Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/kstawiski/OmicSelector/master/vignettes/setup.R");'

      - name: Install package
        run: R CMD INSTALL .

      - name: Check loading
        run: |
          Rscript -e 'library(OmicSelector); sessionInfo();'
