on:
  push:
    branches: master

name: R package

jobs:
  Rpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install enviorment
        run: |
          pwd
          conda update --all
          conda create -n OmicSelector -c conda-forge mamba 
          conda activate OmicSelector
          mamba install --channel "conda-forge" --channel "anaconda" --channel "r" conda-pack tensorflow-gpu keras jupyter jupytext numpy pandas r-base r-devtools r-rgl r-cairo r-rjava r-mnormt r-purrrogress r-xml gxx_linux-64 libxml2 pandoc r-rjava r-magick opencv pkgconfig gfortran_linux-64
          echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile
          Rscript -e 'update.packages(ask = F); install.packages(c("devtools","remotes")); remotes::install_cran("pkgdown");'
          Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/kstawiski/OmicSelector/master/vignettes/setup.R")'
      - name: Install package
        run: R CMD INSTALL .

      - name: Check loading
        run: |
          Rscript -e 'library(OmicSelector); sessionInfo();'
          
      - name: Pack env
        run: | 
          conda pack -n OmicSelector -o OmicSelector_conda_env.tar.gz
          
      # Removes the latest release, so that we can create a new one in its place
      - name: Delete latest release
        uses: ame-yu/action-delete-latest-release@v2
        continue-on-error: true # in case there's no existing release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (optional) Removes the tag associated with the latest release
      - name: Delete release tag
        run: |
          git tag -d release
          git push origin :release
        continue-on-error: true # in case there's no existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: OmicSelector_conda_env.tar.gz
          body: "OmicSelector - latest version (conda env)"
          name: Latest
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
