on:
  push:
    branches: master

name: R package

jobs:
  Rpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install enviorment
        run: |
          conda update --all
          conda install mamba -c conda-forge
          mamba install --channel "conda-forge" --channel "anaconda" --channel "r" python=3.6 r-base=4.0.3 tensorflow keras jupyter jupytext numpy pandas r-devtools r-rgl r-xml gxx_linux-64 libxml2 pandoc r-rjava r-magick gfortran_linux-64
          echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile
          Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/kstawiski/OmicSelector/master/vignettes/setup.R")'

      - name: Install package
        run: R CMD INSTALL .

      - name: Check loading
        run: |
          Rscript -e 'library(OmicSelector); sessionInfo();'
